"""Build the JSON files used by the SHAD website (docs/data/*.json).

Run from the repository root after any change to Dataset/ or Annotations/:

    python Scripts/build_site_data.py

Outputs
-------
docs/data/catalog.json  one entry per series (metadata, events, label segments)
docs/data/metrics.json  documentation of the 171 dimensions
docs/data/stats.json    aggregated statistics (per-dimension label frequency, missing values)
docs/METRICS.md         markdown dictionary of the 171 dimensions
docs/EXPERIMENTS.md     markdown registry of the 215 experiments
"""

import json
import re
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from shad import GROUPS, METRICS, SHAD, metric_info  # noqa: E402

OUT = ROOT / "docs" / "data"


def segments(y):
    d = np.diff(np.r_[0, np.asarray(y, dtype=np.int8), 0])
    return [[int(s), int(e)] for s, e in zip(np.flatnonzero(d == 1), np.flatnonzero(d == -1))]


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    ds = SHAD(ROOT)
    cat = ds.catalog

    series = []
    label_counts = {g: np.zeros(len(METRICS), dtype=int) for g in GROUPS}
    missing = np.zeros(len(METRICS))
    total_points = 0
    for _, row in cat.iterrows():
        s = ds.load(row["id"])
        raw_cols = open(row["csv_path"]).readline()
        host = re.search(r"\b(quarry\s?\d*)", s.explanation)
        n = len(s)
        total_points += n
        missing += s.data.isna().sum().to_numpy()
        lab_dims = s.labels.any().to_numpy()
        label_counts[s.group] += lab_dims.astype(int)
        minutes = (s.data.index - s.data.index[0]).total_seconds().to_numpy() / 60
        gaps = s.data.index.to_series().diff().dt.total_seconds().fillna(60)
        series.append({
            "id": s.id,
            "group": s.group,
            "type": s.type,
            "category": s.category,
            "criticality": s.criticality,
            "explanation": s.explanation,
            "broken_telemetry": bool(row["broken_telemetry"]),
            "legacy_names": raw_cols.count(",s0-") > 0,
            "cluster": host.group(1).replace(" ", "") if host else None,
            "start": s.data.index[0].isoformat(),
            "end": s.data.index[-1].isoformat(),
            "n": n,
            "missing_ratio": round(float(s.data.isna().to_numpy().mean()), 5),
            "gaps": int((gaps > 90).sum()),
            "anomaly_ratio": round(float(s.label.mean()), 5),
            "segments": segments(s.y),  # row indices, end exclusive
            "segments_min": [[round(float(minutes[a]), 1), round(float(minutes[b - 1]) + 1, 1)] for a, b in segments(s.y)],
            "minutes": round(float(minutes[-1]) + 1, 1),
            "labeled_dimensions": [int(i) for i in np.flatnonzero(lab_dims)],
            "events": [{
                "offset": e.offset_minutes, "duration": e.duration_minutes,
                "component": e.component, "store": e.store, "disk": e.disk,
                "degradation": e.degradation, "n_related": len(e.related_dimensions),
            } for e in s.events],
            "path": f"Dataset/{s.group}/{s.id}.csv",
            "annotation": f"Annotations/{s.id}.xml",
        })
        if len(series) % 50 == 0 or len(series) == len(cat):
            print(f"processed {len(series)}/{len(cat)} series")

    metrics = [metric_info(m).__dict__ for m in METRICS]
    stats = {
        "n_series": len(series),
        "n_dimensions": len(METRICS),
        "n_points": int(total_points),
        "groups": GROUPS,
        "dimension_label_counts": {g: v.tolist() for g, v in label_counts.items()},
        "dimension_missing_ratio": (missing / total_points).round(5).tolist(),
    }
    for name, obj in (("catalog", series), ("metrics", metrics), ("stats", stats)):
        with open(OUT / f"{name}.json", "w") as f:
            json.dump(obj, f, separators=(",", ":"))
        print("wrote", OUT / f"{name}.json", f"{(OUT / f'{name}.json').stat().st_size / 1e3:.0f} kB")

    write_markdown(series, metrics)


def _md_escape(s):
    return str(s).replace("|", "\\|")


def write_markdown(series, metrics):
    docs = ROOT / "docs"
    lines = [
        "# SHAD metric dictionary",
        "",
        "The 171 dimensions of every SHAD series, in the column order of the CSV files.",
        "Each dimension `<name>` has a per-dimension label column `label_<name>`.",
        "*Generated by `Scripts/build_site_data.py`.*",
        "",
    ]
    titles = {"platform": "Platform level (cluster aggregates)", "s3": "S3 connector / application level",
              "server": "Server level (x3 storage servers)", "device": "Device level (x7 devices x3 servers)"}
    for level, title in titles.items():
        ms = [m for m in metrics if m["level"] == level]
        lines += [f"## {title} - {len(ms)} dimensions", "", "| # | Column | Store | Device | Unit | Description |",
                  "|---|---|---|---|---|---|"]
        for m in ms:
            i = metrics.index(m) + 1
            lines.append(f"| {i} | `{m['name']}` | {m['store'] or ''} | {m['device'] or ''} | {m['unit']} | {_md_escape(m['description'])} |")
        lines.append("")
    (docs / "METRICS.md").write_text("\n".join(lines))

    lines = [
        "# SHAD experiment registry",
        "",
        f"All {len(series)} series of SHAD, grouped by scenario. Browse them interactively in the "
        "[explorer](https://scality.github.io/shad/explorer.html).",
        "*Generated by `Scripts/build_site_data.py` from the XML annotations and CSV labels.*",
        "",
        "Columns: **Start** = first timestamp (UTC), **Len.** = number of timestamps, "
        "**Anom.** = fraction of anomalous timestamps, **Dims** = number of labelled dimensions.",
        "",
    ]
    for g in GROUPS:
        rows = [s for s in series if s["group"] == g]
        if not rows:
            continue
        lines += [f"## {g} ({len(rows)} series)", "", "| Id | Start (UTC) | Len. | Anom. | Dims | Description |",
                  "|---|---|---|---|---|---|"]
        for s in rows:
            flag = " **[broken telemetry]**" if s["broken_telemetry"] else ""
            lines.append(f"| [`{s['id']}`](https://scality.github.io/shad/explorer.html#id={s['id']}) | "
                         f"{s['start'][:16].replace('T', ' ')} | {s['n']} | {100 * s['anomaly_ratio']:.1f}% | "
                         f"{len(s['labeled_dimensions'])} | {_md_escape(s['explanation'])}{flag} |")
        lines.append("")
    (docs / "EXPERIMENTS.md").write_text("\n".join(lines))
    print("wrote docs/METRICS.md and docs/EXPERIMENTS.md")


if __name__ == "__main__":
    main()
